import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import http from 'node:http';
import path from 'node:path';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
const run=promisify(execFile), portal=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
test('server compatibility, concurrent effort, archive history, live refresh, host guard, and file cap', {timeout:90000}, async t => {
  const repo=await fs.mkdtemp(path.join(os.tmpdir(),'openspec-portal-test-')), root=path.join(repo,'openspec');
  await fs.mkdir(path.join(root,'changes/sample'),{recursive:true});
  await fs.writeFile(path.join(root,'config.yaml'),'schema: spec-driven\n');
  await fs.writeFile(path.join(root,'changes/sample/.openspec.yaml'),'schema: spec-driven\n');
  await fs.writeFile(path.join(root,'changes/sample/proposal.md'),'# Sample\n\n[Design](design.md#why)\n');
  await fs.writeFile(path.join(root,'changes/sample/design.md'),'# Design\n## Why\nChoice.');
  await fs.writeFile(path.join(root,'changes/sample/tasks.md'),'## Work\n- [ ] 1.1 Build it\n');
  await fs.mkdir(path.join(root,'changes/metadata-only'));
  await fs.writeFile(path.join(root,'changes/metadata-only/.openspec.yaml'),'schema: spec-driven\n');
  await fs.mkdir(path.join(root,'schemas/compact/templates'),{recursive:true});
  await fs.writeFile(path.join(root,'schemas/compact/schema.yaml'),'name: compact\nversion: 1\ndescription: Fixture custom schema\nartifacts:\n  - id: brief\n    generates: brief.md\n    description: Brief\n    template: brief.md\n    instruction: Write brief\n    requires: []\n  - id: checklist\n    generates: plan.md\n    description: Work\n    template: plan.md\n    instruction: Write tasks\n    requires: [brief]\napply:\n  requires: [checklist]\n  tracks: plan.md\n');
  await fs.writeFile(path.join(root,'schemas/compact/templates/brief.md'),'# Brief');
  await fs.writeFile(path.join(root,'schemas/compact/templates/plan.md'),'## Work');
  await fs.mkdir(path.join(root,'changes/custom'));
  await fs.writeFile(path.join(root,'changes/custom/.openspec.yaml'),'schema: compact\n');
  await fs.writeFile(path.join(root,'changes/custom/brief.md'),'# Custom');
  await fs.writeFile(path.join(root,'changes/custom/plan.md'),'- [x] 1.1 Custom task');
  await fs.mkdir(path.join(root,'changes/no-specs'));
  await fs.writeFile(path.join(root,'changes/no-specs/.openspec.yaml'),'schema: spec-driven\nskip_specs: true\n');
  await fs.writeFile(path.join(root,'changes/no-specs/proposal.md'),'# Tooling\n## Why\nTooling only.');
  await run('git',['init'],{cwd:repo});
  await run('git',['add','.'],{cwd:repo});
  await run('git',['-c','user.name=Portal Test','-c','user.email=test@example.invalid','commit','-m','Initial'],{cwd:repo});
  const port=4300+Math.floor(Math.random()*500), url=`http://127.0.0.1:${port}`;
  const child=spawn(process.execPath,[path.join(portal,'server.mjs'),'--repo',repo,'--port',String(port)],{windowsHide:true,stdio:['ignore','pipe','pipe']});
  let logs=''; child.stderr.on('data',b=>logs+=b);
  t.after(async()=>{ child.kill(); await new Promise(resolve=>child.once('exit',resolve)); await fs.rm(repo,{recursive:true,force:true}); });
  await new Promise((resolve,reject)=>{ child.stdout.on('data',b=>{if(String(b).includes('OpenSpec Portal:'))resolve();}); child.once('exit',()=>reject(Error(logs))); setTimeout(()=>reject(Error('Startup timeout')),10000).unref(); });
  const get=async()=>{ const r=await fetch(url+'/api/data'); assert.equal(r.status,200,logs); return r.json(); };
  let data=await get();
  assert.equal(data.changes.find(c=>c.id==='metadata-only').title,'Metadata Only');
  assert.ok(data.watcher.healthy);
  assert.equal(data.compatibility.source,'openspec-cli');
  assert.equal(data.changes.find(c=>c.id==='custom').tasksPath,'changes/custom/plan.md');
  assert.equal(data.changes.find(c=>c.id==='custom').tasks.done,1);
  assert.equal(data.changes.find(c=>c.id==='custom').planning.complete,true);
  assert.equal(data.changes.find(c=>c.id==='no-specs').planning.artifacts.find(a=>a.id==='specs').status,'skipped');
  const delta=await (await fetch(url+'/api/data?since='+data.revision)).json();
  assert.equal(delta.documentsDelta,true); assert.equal(delta.docs.length,0);
  assert.equal(data.changes.find(c=>c.id==='sample').tasks.items[0].timeline.provenance,'git-sampled');
  const hostStatus = await new Promise((resolve,reject)=>http.get(url+'/api/data',{headers:{Host:'untrusted.invalid:'+port}},r=>{r.resume();resolve(r.statusCode);}).on('error',reject));
  assert.equal(hostStatus,403);
  const date=new Date().toISOString().slice(0,10), headers={Origin:url,'Content-Type':'application/json'};
  const post=entry=>fetch(url+'/api/effort',{method:'POST',headers,body:JSON.stringify(entry)});
  const entries=Array.from({length:12},(_,i)=>({change:'sample',task:'1.1',date,minutes:1,note:'Save '+i,requestId:'request-'+String(i).padStart(3,'0')}));
  const saves=await Promise.all(entries.map(post));
  assert.ok(saves.every(r=>r.status===201),String(saves.map(r=>r.status)));
  assert.equal((await post(entries[0])).status,200);
  let ledger=JSON.parse(await fs.readFile(path.join(repo,'.openspec-portal/effort.json'),'utf8'));
  assert.equal(ledger.entries.length,12);
  assert.equal((await post({...entries[0],date:'2026-99-01'})).status,400);
  await fs.mkdir(path.join(root,'changes/archive'));
  await fs.rename(path.join(root,'changes/sample'),path.join(root,'changes/archive/2026-09-26-sample'));
  await fs.rename(path.join(root,'changes/custom'),path.join(root,'changes/archive/2026-09-26-custom'));
  await run('git',['add','.'],{cwd:repo});
  await run('git',['-c','user.name=Portal Test','-c','user.email=test@example.invalid','commit','-m','Archive'],{cwd:repo});
  await new Promise(r=>setTimeout(r,500));
  data=await get();
  assert.equal(data.archive.find(c=>c.stableId==='sample').tasks.items[0].timeline.effortMinutes,12);
  assert.equal(data.archive.find(c=>c.stableId==='sample').tasks.items[0].timeline.provenance,'git-sampled');
  assert.equal(data.archive.find(c=>c.stableId==='custom').tasksPath,'changes/archive/2026-09-26-custom/plan.md');
  const validation=await (await fetch(url+'/api/validate')).json();
  assert.equal(validation.source,'openspec-cli'); assert.ok(validation.result);
  const controller=new AbortController(), events=await fetch(url+'/api/events',{signal:controller.signal}), reader=events.body.getReader();
  let stream=new TextDecoder().decode((await reader.read()).value);
  await fs.writeFile(path.join(root,'watch.txt'),'changed');
  const timer=setTimeout(()=>controller.abort(),5000);
  while(!stream.includes('event: change'))stream+=new TextDecoder().decode((await reader.read()).value);
  clearTimeout(timer);controller.abort(); assert.ok(stream.includes('event: ready'));
  await fs.mkdir(path.join(root,'notes')); await Promise.all(Array.from({length:5002},(_,i)=>fs.writeFile(path.join(root,'notes',i+'.txt'),'x')));
  await new Promise(r=>setTimeout(r,500)); data=await get();
  assert.equal(data.docs.length,5000); assert.ok(data.warnings.some(w=>w.includes('5,000')));
});
